# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftSampleApp

  target 'RxSwiftSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftSampleAppUITests' do
    # Pods for testing
  end

pod 'RxSwift'
pod 'RxCocoa'

end
